name = "my-app"
main = "src/index.ts"
compatibility_date = "2025-01-27"
compatibility_flags = [ "nodejs_compat" ]

# DATABASE_URL comes from .dev.vars locally and `wrangler secret put DATABASE_URL` in production.

[vars]
JWT_SECRET = "secret111"
